<?php

/**
 * @file
 * List of included modules.
 */

require_once MODULES_PATH . '/Module.php';

// START_LIST
require_once MODULES_PATH . '/BaseStats/BaseStats.php';
require_once MODULES_PATH . '/Preferences/Preferences.php';
require_once MODULES_PATH . '/TingObjectRating/TingObjectRating.php';
require_once MODULES_PATH . '/ResetUser/ResetUser.php';
require_once MODULES_PATH . '/ListPermission/ListPermission.php';
require_once MODULES_PATH . '/IPAccess/IPAccess.php';
require_once MODULES_PATH . '/SlowLogger/SlowLogger.php';
